# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    person_link_finder:
        class: AppBundle\Service\FindLink
        arguments: ["@doctrine.orm.entity_manager"]
